/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_joker_main_KeyHouse */

#ifndef share_key
#define share_key
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_joker_main_KeyHouse
 * Method:    getWeChatAppId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_joker_main_KeyHouse_getWeChatAppId(JNIEnv *env, jclass clazz) {
  return env->NewStringUTF("wxd930ea5d5a258f4f");
}

/*
 * Class:     com_joker_main_KeyHouse
 * Method:    getWeChatAppSecret
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_joker_main_KeyHouse_getWeChatAppSecret
    (JNIEnv *env, jclass clazz) {
  return env->NewStringUTF("bd27e952106b77ef07a80749024a6352");
}

/*
 * Class:     com_joker_main_KeyHouse
 * Method:    getWeiboKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_joker_main_KeyHouse_getWeiboKey
    (JNIEnv *env, jclass clazz) {
  return env->NewStringUTF("1432934020");
}

#ifdef __cplusplus
}
#endif
#endif
