/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_joker_main_KeyHouse */

#ifndef share_key
#define share_key
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_joker_main_KeyHouse
 * Method:    getWeChatAppId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_joker_main_KeyHouse_getWeChatAppId
  (JNIEnv *, jclass);

/*
 * Class:     com_joker_main_KeyHouse
 * Method:    getWeChatAppSecret
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_joker_main_KeyHouse_getWeChatAppSecret
  (JNIEnv *, jclass);

/*
 * Class:     com_joker_main_KeyHouse
 * Method:    getWeiboKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_joker_main_KeyHouse_getWeiboKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
