package com.joker.test_java;

import org.json.JSONObject;
public class TestClass{
 public static void main(String[] args){
  final String JSON="{\"id\":2681225804,\"screen_name\":\"身从无相中受生\",\"province\":\"11\",\"city\":\"1\",\"location\":\"北京 东城区\",\"description\":\"\",\"url\":\"\",\"profile_image_url\":\"http://tvax2.sinaimg.cn/crop.0.0.108.108.50/9fd0424cly8ffhhg8dyfej2030030wea.jpg\",\"cover_image_phone\":\"http://ww1.sinaimg.cn/crop.0.0.640.640.640/549d0121tw1egm1kjly3jj20hs0hsq4f.jpg\",\"profile_url\":\"u/2681225804\",\"domain\":\"\",\"weihao\":\"\",\"gender\":\"m\",\"followers_count\":22,\"friends_count\":18,\"pagefriends_count\":1,\"statuses_count\":3,\"video_status_count\":0,\"favourites_count\":31,\"created_at\":\"Mon Jan 23 17:14:44 +0800 2012\",\"following\":false,\"allow_all_act_msg\":false,\"geo_enabled\":true,\"verified\":false,\"verified_type\":-1,\"remark\":\"\",\"insecurity\":{\"sexual_content\":false},\"status\":{\"created_at\":\"Wed Nov 16 21:07:56 +0800 2016\",\"id\":4042546591925293,\"idstr\":\"4042546591925293\",\"mid\":\"4042546591925293\",\"can_edit\":false,\"text\":\"mark『写给Android开发者的混淆使用手册』http://t.cn/RVWAJ1m\",\"textLength\":58,\"source_allowclick\":0,\"source_type\":1,\"source\":\"<a href=\\\"http://app.weibo.com/t/feed/UySee\\\" rel=\\\"nofollow\\\">华为麦芒3</a>\",\"favorited\":false,\"truncated\":false,\"in_reply_to_status_id\":\"\",\"in_reply_to_user_id\":\"\",\"in_reply_to_screen_name\":\"\",\"pic_urls\":[],\"geo\":null,\"is_paid\":false,\"mblog_vip_type\":0,\"annotations\":[{\"shooting\":1,\"client_mblogid\":\"65172b83-43a1-4ffa-b10f-409f7dccfdce\"},{\"mapi_request\":true}],\"reposts_count\":0,\"comments_count\":0,\"attitudes_count\":0,\"pending_approval_count\":0,\"isLongText\":false,\"hide_flag\":0,\"mlevel\":0,\"visible\":{\"type\":0,\"list_id\":0},\"biz_ids\":[0],\"biz_feature\":0,\"hasActionTypeCard\":0,\"darwin_tags\":[],\"hot_weibo_tags\":[],\"text_tag_tips\":[],\"mblogtype\":0,\"rid\":\"0\",\"userType\":0,\"more_info_type\":0,\"positive_recom_flag\":0,\"content_auth\":0,\"gif_ids\":\"\",\"is_show_bulletin\":2,\"comment_manage_info\":{\"comment_permission_type\":-1,\"approval_comment_type\":0}},\"ptype\":0,\"allow_all_comment\":true,\"avatar_large\":\"http://tvax2.sinaimg.cn/crop.0.0.108.108.180/9fd0424cly8ffhhg8dyfej2030030wea.jpg\",\"avatar_hd\":\"http://tvax2.sinaimg.cn/crop.0.0.108.108.1024/9fd0424cly8ffhhg8dyfej2030030wea.jpg\",\"verified_reason\":\"\",\"verified_trade\":\"\",\"verified_reason_url\":\"\",\"verified_source\":\"\",\"verified_source_url\":\"\",\"follow_me\":false,\"like\":false,\"like_me\":false,\"online_status\":0,\"bi_followers_count\":0,\"lang\":\"zh-cn\",\"star\":0,\"mbtype\":0,\"mbrank\":0,\"block_word\":0,\"block_app\":0,\"credit_score\":80,\"user_ability\":0,\"urank\":4,\"story_read_state\":-1,\"vclub_member\":0}";
  JSONObject object=new JSONObject(JSON);
  System.out.println(object.getLong("id"));
 }
}
